analyzer:
  errors:
    camel_case_types: ignore
    constant_identifier_names: ignore
    file_names: ignore
    non_constant_identifier_names: ignore
include: package:lints/recommended.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
