name: util_xx
description: "节流、防抖、重复触发、限制单次触发、流"
version: 0.2.3
homepage: https://github.com/coolight7/util_xx

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.2.0 # 日志
  string_util_xx:

dev_dependencies:
  test:
  lints: